build:
 verbosity: detailed
image: Visual Studio 2017
platform: x64
environment:
  matrix:
   - COMMIT: fb0c047
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
   - COMMIT: 208bb8e
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
build_script:
  - |-
     git clone https://github.com/microsoft/vcpkg.git
     cd vcpkg
     git reset --hard %COMMIT%
     git status
     git show HEAD --no-patch
     echo.set(VCPKG_BUILD_TYPE release)>> triplets\x64-windows.cmake
     call bootstrap-vcpkg.bat
     where vcpkg
     vcpkg version
     vcpkg --triplet x64-windows install boost
on_failure:
  - cmd: type C:\Tools\vcpkg\buildtrees\boost-fiber\build-x64-windows-rel-out.log
