build:
 verbosity: detailed
image: Visual Studio 2017
platform: x64
environment:
  matrix:
   - COMMIT: 1b2f75b
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
   - COMMIT: HEAD
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
build_script:
  - |-
     git clone https://github.com/microsoft/vcpkg.git
     cd %APPVEYOR_BUILD_FOLDER%\vcpkg
     git reset --hard %COMMIT%
     git status
     git show HEAD --no-patch
     echo.set(VCPKG_BUILD_TYPE release)>> %APPVEYOR_BUILD_FOLDER%\vcpkg\triplets\x64-windows.cmake
     call bootstrap-vcpkg.bat
     %APPVEYOR_BUILD_FOLDER%\vcpkg\vcpkg.exe version
     %APPVEYOR_BUILD_FOLDER%\vcpkg\vcpkg.exe --triplet x64-windows install boost
on_failure:
  - cmd: type buildtrees\boost-fiber\build-x64-windows-rel-out.log
