build:
 verbosity: detailed
image: Visual Studio 2017
platform: x64
environment:
  matrix:
   - BUILDNUM: 1
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
   - BUILDNUM: 2
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
build_script:
  - |-
     git clone https://github.com/microsoft/vcpkg.git
     cd vcpkg
     if "%BUILDNUM%" == "1" ( git checkout 208bb8e ) ELSE ( git checkout 22e0b9f )
     git reset --hard
     git status
     echo.set(VCPKG_BUILD_TYPE release)>> triplets\x64-windows.cmake
     call bootstrap-vcpkg.bat
     where vcpkg
     vcpkg version
     vcpkg --triplet x64-windows install boost
on_failure:
  - cmd: type C:\Tools\vcpkg\buildtrees\boost-fiber\build-x64-windows-rel-out.log
